name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Go to Directory
        run: cd arktur-frontend
      - name: Install packages
        run: npm i
      - name: Deploy
        run: npm run deploy
